language: java
before_script:
  - mysql -u root -e 'CREATE DATABASE job;'
install:
  - mvn install -DskipTests
script:
  - mvn flyway:migrate
  - jdk_switcher use oraclejdk8
  - mvn test
services:
  - mysql
env:
  - DB_PASS=""