language: java
before_script:
  - mysql -u root -e 'CREATE DATABASE job;'
install:
  - mvn install -Dmaven.test.skip=true
script:
  - mvn flyway:migrate
  - mvn test -Ptravis
services:
  - mysql
env:
  - DB_PASS=""